choco install -y GoogleChrome
choco install -y vlc
choco install -y spotify
choco install -y steam
choco install -y abodereader
choco install -y Cygwin
choco install -y notepadplusplus
choco install -y resilio-sync-home
choco install -y dropbox
