Get-AppxPackage 828B5831* | remove-appxpackage
get-appxpackage A278AB0D* | remove-appxpackage
get-appxpackage Nordcurrent* | remove-appxpackage
get-appxpackage king.com* | remove-appxpackage
get-appxpackage *bing* | remove-appxpackage
get-appxpackage *store* | remove-appxpackage
get-appxpackage *zune* | remove-appxpackage
get-appxpackage Microsoft.Wallet | remove-appxpackage
get-appxpackage Microsoft.Messaging | remove-appxpackage
get-appxpackage Microsoft.Microsoft3DViewer | remove-appxpackage
get-appxpackage Microsoft.Advertising.Xaml | remove-appxpackage
get-appxpackage Microsoft.Print3D | remove-appxpackage
get-appxpackage Microsoft.OneConnect | remove-appxpackage
get-appxpackage Microsoft.WindowsMaps | remove-appxpackage
get-appxpackage Microsoft.WebMediaExtensions | remove-appxpackage
get-appxpackage Microsoft.People | remove-appxpackage
get-appxpackage Microsoft.WindowsCamera | remove-appxpackage
get-appxpackage WindowsFeedbackHub | remove-appxpackage
get-appxpackage Microsoft.MicrosoftOfficeHub | remove-appxpackage
get-appxpackage DesktopAppInstaller | remove-appxpackage