MY_PROJECTS_DIR="$HOME/Documents/personal/projects"

alias isodate='date -u +%Y-%m-%dT%H:%M:%SZ'
alias me='cd "$MY_PROJECTS_DIR"'
alias wipe='clear && printf "\e[3J"'

# Will only have to download things once.
git_version="v$(git version | awk '{print $NF}')"
if [[ "$0" == *zsh* ]]; then
    completion_file="$HOME/.git-$git_version-completion.zsh"
    function_file="$HOME/.zsh/functions/_git"
    if [ ! -f "$completion_file" ]; then
        curl -sSL "https://raw.githubusercontent.com/git/git/$git_version/contrib/completion/git-completion.zsh" > "$completion_file"
        mkdir -p "$(dirname $function_file)"
        cp "$completion_file" "$function_file"
    fi

    # Older/newer versions of zsh may need "~/.zsh/functions"?
    fpath=(~/.zsh $fpath)
    autoload -Uz compinit && compinit
elif [[ "$0" == *bash* ]]; then
    completion_file="$HOME/.git-$git_version-completion.bash"
    if [ ! -f "$completion_file" ]; then
        curl -sSL "https://raw.githubusercontent.com/git/git/$git_version/contrib/completion/git-completion.bash" > "$completion_file"
    fi

    # May have to look into restoring some functionality from:
    #  https://github.com/Eagerod/dotfiles/blob/ce33011/git/git.sh#L16-L23
    # If using Cygwin anytime soon.

    source "$completion_file"
else
   echo >&2 "Shell ($0) not configured for git completion."
fi

prompt_file="$HOME/.git-$git_version-prompt.sh"
if [ ! -f "$prompt_file" ]; then
    curl -fsSL "https://raw.githubusercontent.com/git/git/$git_version/contrib/completion/git-prompt.sh" > "$prompt_file"
fi
source "$prompt_file"

unset git_version prompt_file completion_file function_file

if [ "$(uname)" = "Linux" ]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
    alias open='xdg-open'
elif [ "$(uname)" = "Darwin" ]; then
    alias showhidden='defaults write com.apple.finder AppleShowAllFiles YES && killall Finder'
    alias hidehidden='defaults write com.apple.finder AppleShowAllFiles NO && killall Finder'
fi

if [ ! -z "$(git -C "$MY_PROJECTS_DIR/dotfiles" status --porcelain)" ]; then
    echo >&2 "Dotfiles have changed..."
fi

# Provided to explicitly have custom behaviour on machines used for different
#   purposes.
if [ -f ~/.bash_profile_extra ]; then
    source ~/.bash_profile_extra
fi
